spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3308/lab_management?serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: 0966420942
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      repositories:
        enabled: false
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        #        format_sql: true
        jdbc:
          time_zone: Asia/Ho_Chi_Minh  #VietNam
          use_fractional_seconds: true
        dialect: org.hibernate.dialect.MySQLDialect  # Sử dụng dialect hỗ trợ MySQL 8+ với microseconds
  jackson:
    date-format: "dd/MM/yyyy"
    serialization:
      write-dates-as-timestamps: true
  mail:
    host: localhost
    port: 1025
    username: admin@sang
    password: 12345678
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connection timeout: 5000
        timeout: 3000
        write-timeout: 5000
  cache:
    type: redis
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 8640000 # a day
      refresh-token:
        expiration: 604800000 #7 days
  cors:
    origins: "http://localhost:5173,http://localhost:5174"
  mailing:
    expiration: 300 # 5 minutes
    backend:
      activation-url: http://localhost:8080/api/v1/auth/activate-account
    success-url: http://localhost:5173/success?activated=true
    error-url: http://localhost:5173/error?message=
logging:
  level:
    root: INFO
    com.example: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.cache: TRACE
    org.springframework.data.redis: DEBUG
  file:
    name: logs/spring-boot-app.log
server:
  port: 8080
