spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3308/lab_management
    username: root
    password: 0966420942
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
  mail:
    host: localhost
    port: 1025
    username: admin@sang
    password: 12345678
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connection timeout: 5000
        timeout: 3000
        write-timeout: 5000

application:
  security:
    jwt:
      secret-key: 404E635266526A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 8640000 # a day
      refresh-token:
        expiration: 604800000 #7 days
  mailing:
    backend:
      activation-url: http://localhost:8080/api/v1/auth/activate-account
    success-url: http://localhost:5173/success?activated=true
    error-url: http://localhost:5173/error?message=

#stripe:
#  api:
#    key: sk_test_51Pc7hZRouRzOhclz6afLEJZpKoRZb10IASVHpRk8zhYokrsVeJAiHUgJp4Gn7f5NO15G7KV4Q7EDMqNY4WcWL7qY00kUikEkD3
server:
  port: 8080
