spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3308/lab_management?serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: 0966420942
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Ho_Chi_Minh  #VietNam
          use_fractional_seconds: true
        # Giới thiệu các tùy chọn bổ sung cho Hibernate
        dialect: org.hibernate.dialect.MySQL8Dialect  # Sử dụng dialect hỗ trợ MySQL 8+ với microseconds
  jackson:
    date-format: "dd/MM/yyyy"
    serialization:
      write-dates-as-timestamps: true
  mail:
    host: localhost
    port: 1025
    username: admin@sang
    password: 12345678
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connection timeout: 5000
        timeout: 3000
        write-timeout: 5000
application:
  security:
    jwt:
      secret-key: 404E635266526A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 8640000 # a day
      refresh-token:
        expiration: 604800000 #7 days
  mailing:
    backend:
      activation-url: http://localhost:8080/api/v1/auth/activate-account
      reset-password-url: http://localhost:8080/api/v1/auth/reset-password
    success-url: http://localhost:5173/success?activated=true
    error-url: http://localhost:5173/error?message=
server:
  port: 8080
